-- Table: observations
-- Source: HMUObservation.py (create_redshift_tables_sql)
-- Extracted: extract_ddl_from_glue_jobs.py

-- Main observations table
    CREATE TABLE IF NOT EXISTS public.observations (
        observation_id VARCHAR(255) NOT NULL,
        patient_id VARCHAR(255) NOT NULL,
        encounter_id VARCHAR(255),
        specimen_id VARCHAR(255),
        status VARCHAR(50),
        observation_text VARCHAR(500),
        primary_code VARCHAR(50),
        primary_system VARCHAR(255),
        primary_display VARCHAR(255),
        value_string VARCHAR(500),
        value_quantity_value DECIMAL(15,4),
        value_quantity_unit VARCHAR(50),
        value_quantity_system VARCHAR(255),
        value_codeable_concept_code VARCHAR(50),
        value_codeable_concept_system VARCHAR(255),
        value_codeable_concept_display VARCHAR(255),
        value_codeable_concept_text VARCHAR(500),
        value_datetime TIMESTAMP,
        value_boolean BOOLEAN,
        data_absent_reason_code VARCHAR(50),
        data_absent_reason_display VARCHAR(255),
        data_absent_reason_system VARCHAR(255),
        effective_datetime TIMESTAMP,
        effective_period_start TIMESTAMP,
        effective_period_end TIMESTAMP,
        issued TIMESTAMP,
        body_site_code VARCHAR(50),
        body_site_system VARCHAR(255),
        body_site_display VARCHAR(255),
        body_site_text VARCHAR(500),
        method_code VARCHAR(50),
        method_system VARCHAR(255),
        method_display VARCHAR(255),
        method_text VARCHAR(500),
        meta_last_updated TIMESTAMP,
        meta_source VARCHAR(255),
        meta_profile TEXT,
        meta_security TEXT,
        meta_tag TEXT,
        extensions TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) DISTKEY (patient_id) SORTKEY (patient_id, effective_datetime)
